// <auto-generated />
using System;
using Kiss_Milan_backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kiss_Milan_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260216173122_DefaultHirdetesDatum")]
    partial class DefaultHirdetesDatum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Kiss_Milan_backend.Models.ingatlanok", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ar")
                        .HasColumnType("int");

                    b.Property<DateTime>("hirdetesDatuma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("kategoria")
                        .HasColumnType("int");

                    b.Property<string>("kepUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("leiras")
                        .HasColumnType("longtext");

                    b.Property<bool>("tehermentes")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("id");

                    b.HasIndex("kategoria");

                    b.ToTable("ingatlanoks");
                });

            modelBuilder.Entity("Kiss_Milan_backend.Models.kategoriak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("kategoriaks");
                });

            modelBuilder.Entity("Kiss_Milan_backend.Models.ingatlanok", b =>
                {
                    b.HasOne("Kiss_Milan_backend.Models.kategoriak", "Kategoria")
                        .WithMany()
                        .HasForeignKey("kategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategoria");
                });
#pragma warning restore 612, 618
        }
    }
}
